### ISSUE TITLE
UserWithId Strategy calls id() method on User Model

### ISSUE THREAD

**Issue by vinnyvimto** [laravel-unleash/laravel-unleash#30]
https://github.com/mikefrancis/laravel-unleash/blob/d370d33e99629b3780977146efec02e97c1c7068/src/Strategies/UserWithIdStrategy.php#L19

Method here should be `getKey()`. Calling `id()` leads to a BadMethodCallException `Call to undefined method App\Models\User::id()`.

Publishing the config also adds the default strategy "userWithId**s**" when the unleashed API returns the strategy as the singular "userWithId".

**Comment by mikefrancis** [comment]
@vinnyvimto It seems like you know how to fix the issue, would be great if you could raise a PR instead?

**Comment by rfussien** [comment]
Hello,

Why has it been closed ? This bug is preventing this project to work properly with the basic features of unleash. :/

**Comment by mikefrancis** [comment]
@rfussien If it's so important, can I ask if there  issomething preventing you from PRing a fix?

**Comment by mikefrancis** [comment]
@vinnyvimto 

`$user` on [this line](https://github.com/mikefrancis/laravel-unleash/blob/master/src/Strategies/UserWithIdStrategy.php#L15) should be an instance of either `Illuminate\Contracts\Auth\Guard` or `null` from looking at the [framework source](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Http/Request.php#L529-L538).

The strategy checks for `null`, and any `Guard` _has_ to implement the `id()` method, so this looks like a problem with your guard? Are you using something custom which doesn't implement that method?

**Comment by rneal-ck** [comment]
@mikefrancis We're running into the same issue as @vinnyvimto on our end – my understanding is the framework source link above calls `getUserResolver()` with the `$guard` as a parameter, but returns a `Illuminate\Foundation\Auth\User`, not the `Illuminate\Contracts\Auth\Guard`. I updated the PR I pushed to use `getAuthIdentifier()` (from `Illuminate\Auth\Authenticatable`, which `User` implements) instead of `id()`, which is working on our end now and should fix the tests as well.
